#ifndef MUSLIMTIFY_FONTS_H
#define MUSLIMTIFY_FONTS_H

#define FONT_SIZE_TITLE_LARGE 48
#define FONT_SIZE_TITLE_MEDIUM 42
#define FONT_SIZE_TITLE_SMALL 36

#define FONT_SIZE_BODY_LARGE 36
#define FONT_SIZE_BODY_MEDIUM 24
#define FONT_SIZE_BODY_SMALL 18

#define FONT_SIZE_CAPTION_LARGE 16
#define FONT_SIZE_CAPTION_MEDIUM 14
#define FONT_SIZE_CAPTION_SMALL 12

extern int FONT_MANROPE_BOLD;
extern int FONT_MANROPE_REGULAR;

void muslimtify_fonts_load(void);

#endif // MUSLIMTIFY_FONTS_H
