#requires -Version 5.1
# Regenerates src/platform/windows/windows_zones_generated.inc from the vendored
# CLDR windowsZones.xml. Maintainer-only, offline tool. NOT part of the CMake
# build or CI.
#
# Usage (from repo root):
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts/gen-windows-zones.ps1
#   # pwsh scripts/gen-windows-zones.ps1   also works
#
# To update on a CLDR release: replace vendor/cldr/windowsZones.xml, rerun this
# script, reconcile $overrides against tests/test_location.c, commit the diff.
# See vendor/cldr/README.md.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$xmlPath  = Join-Path $repoRoot 'vendor\cldr\windowsZones.xml'
$outPath  = Join-Path $repoRoot 'src\platform\windows\windows_zones_generated.inc'

if (-not (Test-Path -LiteralPath $xmlPath)) {
    throw "windowsZones.xml not found at $xmlPath"
}

# Per Windows zone, these IANA names are emitted FIRST (in this order), so the
# linear reverse scan in windows_zone_to_iana() returns the first one. Any name
# absent from CLDR is added; any already present is moved to the front.
# Rationale:
#   - CLDR records these zones under legacy tz aliases; prefer the modern
#     canonical name, keep the legacy one as a following alias:
#       India     -> Asia/Kolkata                   (CLDR: Asia/Calcutta)
#       Nepal     -> Asia/Kathmandu                 (CLDR: Asia/Katmandu)
#       Myanmar   -> Asia/Yangon                    (CLDR: Asia/Rangoon)
#       Argentina -> America/Argentina/Buenos_Aires (CLDR: America/Buenos_Aires)
#   - Asia/Jakarta over CLDR's Asia/Bangkok: Indonesia-first for this prayer app.
#   - bare "UTC" kept alongside Etc/UTC to preserve timezone_exists("UTC")==true.
$overrides = [ordered]@{
    'Argentina Standard Time' = @('America/Argentina/Buenos_Aires')
    'SE Asia Standard Time'   = @('Asia/Jakarta')
    'Nepal Standard Time'     = @('Asia/Kathmandu')
    'India Standard Time'     = @('Asia/Kolkata')
    'Myanmar Standard Time'   = @('Asia/Yangon')
    'UTC'                     = @('Etc/UTC', 'UTC')
}

# CLDR's supplemental XML references an external DTD via DOCTYPE; ignore it so a
# plain [xml] cast does not try (and fail) to resolve it offline.
$settings = New-Object System.Xml.XmlReaderSettings
$settings.DtdProcessing = [System.Xml.DtdProcessing]::Ignore
$settings.XmlResolver = $null
$reader = [System.Xml.XmlReader]::Create($xmlPath, $settings)
$doc = New-Object System.Xml.XmlDocument
try { $doc.Load($reader) } finally { $reader.Close() }

# winZone -> ordered unique IANA list. CLDR lists the territory="001" canonical
# first per zone, so the first inserted name is the canonical (before overrides).
$groups = [ordered]@{}
foreach ($mz in $doc.supplementalData.windowsZones.mapTimezones.mapZone) {
    $win = [string]$mz.other
    $ianas = ([string]$mz.type).Trim() -split '\s+' | Where-Object { $_ -ne '' }
    if (-not $groups.Contains($win)) {
        $groups[$win] = [System.Collections.Generic.List[string]]::new()
    }
    foreach ($ia in $ianas) {
        if (-not $groups[$win].Contains($ia)) { [void]$groups[$win].Add($ia) }
    }
}

# Apply overrides: move override names to the front (in order), adding if absent.
foreach ($win in $overrides.Keys) {
    if (-not $groups.Contains($win)) {
        throw "Override references a Windows zone absent from CLDR: $win"
    }
    $list = $groups[$win]
    $names = $overrides[$win]
    for ($i = $names.Count - 1; $i -ge 0; $i--) {
        [void]$list.Remove($names[$i])
        $list.Insert(0, $names[$i])
    }
}

# Emit grouped by Windows zone, canonical (index 0) first; groups sorted by the
# canonical IANA name for a stable, diffable file.
$rows = [System.Collections.Generic.List[string]]::new()
foreach ($win in ($groups.Keys | Sort-Object { $groups[$_][0] })) {
    foreach ($ia in $groups[$win]) {
        [void]$rows.Add(('{{"{0}", L"{1}"}},' -f $ia, $win))
    }
}

if ($rows.Count -lt 300) {
    throw "Only $($rows.Count) rows generated; expected ~450. Aborting."
}

$lines = @(
    '// Generated by scripts/gen-windows-zones.ps1 from vendor/cldr/windowsZones.xml.',
    '// DO NOT EDIT BY HAND. See vendor/cldr/README.md to regenerate.',
    ('// {0} entries, grouped by Windows zone, canonical IANA first.' -f $rows.Count)
) + $rows

# LF line endings, UTF-8 without BOM, single trailing newline.
[IO.File]::WriteAllText($outPath, ($lines -join "`n") + "`n",
    (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $($rows.Count) entries to $outPath"
